apiVersion: spdx.softwarecomposition.seclogic.io/v1beta1
kind: NetworkNeighborhood
metadata:
  name: deployment-nginx
  annotations:
    seclogic.io/status: ready
  labels:
      "seclogic.io/workload-api-group": "apps"
      "seclogic.io/workload-api-version": "v1"
      "seclogic.io/workload-name": "nginx"
      "seclogic.io/workload-kind": "deployment"
      "seclogic.io/workload-namespace": "seclogic"
  
spec:
  matchLabels:
      app: nginx

  containers:
    - name: nginx
      ingress:
      - type: internal
        identifier: bla
        namespaceSelector:
            matchLabels:
              name: seclogic
        podSelector:
            matchLabels:
              app: seclogic-ui
        ports:
        -   name: TCP-6379
            protocol: TCP
            port: 6379

      egress:
      - type: external
        identifier: bla
        ipAddress: 123.5.2.3
        dns: stripe.com
        ports:
        - name: TCP-5978
          protocol: TCP
          port: 5978
