apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.spdx.softwarecomposition.seclogic.io
spec:
  insecureSkipTLSVerify: true
  group: spdx.softwarecomposition.seclogic.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: wardle
  version: v1beta1
